name: Weekly Reddit Fitness Monitor

on:
  schedule:
    # Run every Monday at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  reddit-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw==7.7.1 python-dotenv==1.0.0 requests==2.31.0
          
      - name: Run Reddit Monitor
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          python reddit_monitor.py
          
      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reddit-report-${{ github.run_number }}
          path: "*.html"
          retention-days: 30
          
      - name: Commit and push report
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.html || true
          git commit -m "Add weekly report $(date +%Y-%m-%d)" || exit 0
          git push || exit 0
